import type {Lang} from './i18n';
export const pick=<T>(x:Record<Lang,T>,l:Lang)=>x[l];
export const common={
trust:{en:['Board-Certified Expertise','Complex Reconstruction','International Care'],ru:['Сертифицированная экспертиза','Сложная реконструкция','Международный сервис'],ar:['خبرة معتمدة','إعادة بناء معقدة','رعاية دولية']},
journey:{en:['Request consultation','Medical records review','Online specialist consultation','Personalized treatment plan','Travel to Dubai','Procedure & recovery','Remote follow-up'],ru:['Запрос консультации','Разбор медицинских документов','Онлайн-консультация специалиста','Индивидуальный план лечения','Поездка в Дубай','Операция и восстановление','Дистанционное наблюдение'],ar:['طلب الاستشارة','مراجعة السجلات الطبية','استشارة اختصاصي عبر الإنترنت','خطة علاج شخصية','السفر إلى دبي','الإجراء والتعافي','متابعة عن بُعد']},
achievements:{en:['Pioneer of Total Ankle Replacement in Los Angeles','Board Certified in Foot Surgery','Board Certified in Reconstructive Rearfoot & Ankle Surgery','International Surgical Educator'],ru:['Пионер эндопротезирования голеностопа в Лос-Анджелесе','Сертифицирован в хирургии стопы','Сертифицирован в реконструктивной хирургии заднего отдела стопы и голеностопа','Международный наставник хирургов'],ar:['رائد استبدال مفصل الكاحل في لوس أنجلوس','معتمد في جراحة القدم','معتمد في جراحة إعادة بناء مؤخرة القدم والكاحل','مدرب جراحي دولي']},
whyTitles:{en:['International Expertise','One Specialized Team','Complex Case Review','Global Patient Support'],ru:['Международная экспертиза','Единая специализированная команда','Разбор сложных случаев','Поддержка международных пациентов'],ar:['خبرة دولية','فريق تخصصي واحد','مراجعة الحالات المعقدة','دعم المرضى الدوليين']},
whyText:{en:['Advanced surgical leadership and evidence-based pathways.','Focused care for the complete foot and ankle journey.','Structured evaluation for revision, deformity and limb-threatening disease.','Remote records review, travel planning and coordinated follow-up.'],ru:['Современное хирургическое руководство и доказательные протоколы.','Сфокусированная помощь на всём пути лечения стопы и голеностопа.','Структурированная оценка ревизионных операций, деформаций и угрозы конечности.','Дистанционный разбор документов, планирование поездки и координация наблюдения.'],ar:['قيادة جراحية متقدمة ومسارات علاج مبنية على الدليل.','رعاية متخصصة طوال رحلة علاج القدم والكاحل.','تقييم منظم للجراحات التصحيحية والتشوهات والحالات المهددة للأطراف.','مراجعة عن بُعد وتخطيط السفر والمتابعة المنسقة.']}
};
